parameters:
#    applester_queue.example.class: Applester\QueueBundle\Example

services:
#    applester_queue.example:
#        class: %applester_queue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
