Applester\QueueBundle\Entity\Token:
  type: entity
  table: token
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    code:
      type: string
      length: 50
    start:
      type: datetime
    end:
      type: datetime
    enabled:
      type: boolean
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
